# Generated by Django 2.0.6 on 2018-06-11 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_calculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='body',
        ),
        migrations.AddField(
            model_name='calculator',
            name='operand_one',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='operand_two',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='operator',
            field=models.CharField(default='+', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='result',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
